### ISSUE TITLE
[EnderStorage-1.12.2-2.4.3.130] Dedicated server : java.lang.NoSuchMethodError: codechicken.lib.render.particle.CustomParticleHandler.addLandingEffects

### ISSUE THREAD

**Issue by TigerWalts** [TheCBProject/Feedback#26]
EnderStorage is attempting to call `CustomParticleHandler.addLandingEffects` from CCL but the method is only available on the client side. A check of the source of the current recommended versions (ES: `2.4.3.131`, CCL: `3.1.9.344`) reveals that this is still the case.

Crash Report from the Enigmatica 2 modpack: [https://pastebin.com/PnumKUbT](https://pastebin.com/PnumKUbT)

```
Description: Ticking entity

java.lang.NoSuchMethodError: codechicken.lib.render.particle.CustomParticleHandler.addLandingEffects(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Lcodechicken/lib/vec/Vector3;I)V
	at codechicken.enderstorage.block.BlockEnderStorage.addLandingEffects(BlockEnderStorage.java:276)
	at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:208)
...
```

**Comment by covers1624** [comment]
This was fixed.
